name: skillshare_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  transparent_image: ^2.0.1
  flutter_animate: ^4.5.0
  flip_card: ^0.7.0
  webview_flutter: ^4.5.0
  shared_preferences: ^2.2.2
  meta: ^1.10.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
